apiVersion: skaffold/v2beta26
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: '{{ .REVISION }}'
  artifacts:
  - image: 839217260075.dkr.ecr.ap-northeast-1.amazonaws.com/feedback/feedback-front
    context: ../../feedback_front
    docker:
      dockerfile: ../environments/front/Dockerfile
      buildArgs:
        endpoint: '{{ .API_ENDPOINT }}'
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: feedback-front
      chartPath: charts
      valuesFiles:
        - '{{ .VALUE_FILE }}'
      artifactOverrides:
        image: 839217260075.dkr.ecr.ap-northeast-1.amazonaws.com/feedback/feedback-front