apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: 839217260075.dkr.ecr.ap-northeast-1.amazonaws.com/feedback/feedback-api
    context: ../../feedback
    docker:
      dockerfile: ../environments/app/Dockerfile
  local:
    useBuildkit: true
profiles:
- name: prd
  deploy:
    helm:
      releases:
      - name: feedback-api
        chartPath: charts
        setValues:
          imagePullPolicy: Always
        artifactOverrides:
          image: 839217260075.dkr.ecr.ap-northeast-1.amazonaws.com/feedback/feedback-api