apiVersion: skaffold/v2beta26
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: '{{ .REVISION }}'
  artifacts:
  - image: feedback-api
    context: ../../feedback
    docker:
      dockerfile: ../environments/app/Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: feedback-api
      chartPath: charts
      artifactOverrides:
        image: feedback-api
