apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts: 
  - image: feedback-db
    context: .
    docker:
      dockerfile: ./Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: feedback-db
      chartPath: charts
      artifactOverrides:
        image: feedback-db