apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts: 
  - image: 839217260075.dkr.ecr.ap-northeast-1.amazonaws.com/feedback/feedback-db
    context: .
    docker:
      dockerfile: ./Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: feedback-db
      chartPath: charts
      setValues:
        imagePullPolicy: Always
      artifactOverrides:
        image: 839217260075.dkr.ecr.ap-northeast-1.amazonaws.com/feedback/feedback-db